# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c

before_install:
  - gem install xcpretty
  - carthage update

script:
- xcodebuild test -scheme DVB-macOS | xcpretty
- xcodebuild test -scheme DVB-iOS | xcpretty
- swift test
# - pod lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
